#!/bin/bash
set -Ceux

ARGS=${@:2}

case $1 in
"up")
  docker compose up -d
;;
"down")
  docker compose down
;;
"start")
  docker compose build --no-cache
  docker compose up -d
  docker compose exec app bash
;;
"quick:firefox")
  docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-firefox:4.1.3-20220405
;;
"quick:chrome")
  docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:4.1.3-20220405
;;
"quick:edge")
  docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-edge:4.1.3-20220405
;;
*)
  echo Unexpected command.
;;
esac
